@URL=http://localhost/cc53b/5.FrontBack/webapp/api
#JWT de Usuário:
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJub21lIjoiSnVjYSBkZSBPbGl2ZWlyYSIsImVtYWlsIjoianVjYW9saXZlaXJhQGdtYWlsLmNvbSIsImFkbWluIjoiMCJ9.LjMNb9AJINmj7_UsrRE7UqN8Xn8Hb0VRk68kV1YASVE

### JWT Admin
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJub21lIjoiQW5hIE1hcmlhIiwiZW1haWwiOiJhbmFAZ21haWwuY29tIiwiYWRtaW4iOiIxIn0.UqttgaMSd9FwlCjgDNnHpXc1y9eLY-21G8Z7xV9HQ9M


### -----------------------------------------
### Criar um produto
POST {{URL}}/produto/create.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "nome":"Geladeira",
    "descricao": "Geladeira 480L",
    "categoria_id": 1,
    "imagem": null,
    "preco": 3000,
    "quantidade": 30
}
### -----------------------------------------



### -----------------------------------------
### Atualizar um produto
POST {{URL}}/produto/update.php?id=1
Content-Type: application/json
Authorization: {{JWT}}

{
    "nome":"Televisor LG 55",
    "descricao":"Televisor LED de 55''...",
    "categoria_id": 2,
    "imagem": "prod.jpg",
    "preco": 3500,
    "quantidade": 40
}
### -----------------------------------------



### -----------------------------------------
### Obter todos os produtos
GET {{URL}}/produto/get.php
### -----------------------------------------



### -----------------------------------------
### Obter todos os produtos de uma categoria
GET {{URL}}/produto/get.php?categoria=1
### -----------------------------------------


### -----------------------------------------
### Obter um produto pelo ID
GET {{URL}}/produto/get.php?id=1
### -----------------------------------------



### -----------------------------------------
### Deletar um produto
GET {{URL}}/produto/delete.php?id=2
Authorization: {{JWT}}
### -----------------------------------------